# Generated by Django 4.2 on 2024-12-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='more_info',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
