# Generated by Django 4.2 on 2024-12-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_subdivision_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subdivisions',
            field=models.ManyToManyField(blank=True, related_name='subdivisions', to='models.subdivision'),
        ),
    ]
